[versions]
# libraries
junit = "4.13.2"
lombok = "1.18.34"
guava = "33.2.1-jre"
druid = "1.2.23"
jsqlparser = "5.0"
evoInflector = "1.3"
annotations = "24.1.0"

# plugins
changelog = "2.2.1"
intelliJPlatform = "2.0.1"
kotlin = "1.9.25"
kover = "0.8.3"
qodana = "2024.1.9"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
druid = { group = "com.alibaba", name = "druid", version.ref = "druid" }
jsqlparser = { group = "com.github.jsqlparser", name = "jsqlparser", version.ref = "jsqlparser" }
evoInflector = { group = "org.atteo", name = "evo-inflector", version.ref = "evoInflector" }
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }


[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
